---
title: "LUEM_assignment3"
author: "Lu Yii Wong & Yujin Song"
date: "2024-03-22"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

## Setup
```{r setup, warning = FALSE, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(pscl)
library(plotROC)
library(pROC)
library(sf)
library(tidyverse)
library(knitr)
library(kableExtra)
library(tigris)
library(viridis)
```

```{r themes}
mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

```


```{r load data}
# dependent variable
inundation <- read.csv("https://raw.githubusercontent.com/luyiiw/LUEM/main/calgary_table/zonal_depe.csv")

# independent variables
elevation <- read.csv("https://raw.githubusercontent.com/luyiiw/LUEM/main/calgary_table/zonal_elev.csv")

flow_acc <- read.csv("https://raw.githubusercontent.com/luyiiw/LUEM/main/calgary_table/zonal_fac.csv")

land_use <- read.csv("https://raw.githubusercontent.com/luyiiw/LUEM/main/calgary_table/zonal_lulc.csv")

slope <- read.csv("https://raw.githubusercontent.com/luyiiw/LUEM/main/calgary_table/zonal_slope.csv")

water_body <- read.csv("https://raw.githubusercontent.com/luyiiw/LUEM/main/calgary_table/zonal_water.csv")

```


Exploratory Analysis
```{r}
# Creating tables to combine exploratory data
flood <- inundation %>%
  select(OBJECTID, RANGE) %>%
  rename(flood = RANGE) %>%
  mutate(flood = factor(flood))

# 1 = flood, 0 = no flood

#1 Elevation
elev_comb <- elevation %>%
  select(OBJECTID, MEAN) %>%
  rename(mean_elev= MEAN)

#2 Slope
slope_comb <- slope %>%
  select(OBJECTID, MAX) %>%
  rename(max_slope= MAX)
# maybe consider mean for model

#3 Water body
water_comb <- water_body %>%
  select(OBJECTID, MIN) %>%
  rename(min_dist_water= MIN)

#4 Flow accumulation
fac_comb <-  flow_acc %>%
  select(OBJECTID, MEAN) %>%
  rename(mean_fac= MEAN)
#changed from max to mean

#5 Land Use/Permeability
# Use max, it's dummy var, as.factor
lu_comb <- land_use %>%
  select(OBJECTID, MAX)%>%
  rename(land_use = MAX) %>%
  mutate(land_use = factor(land_use))

# Urban = 1 , non-urban = 0


# Combining the tables (think of another way to do this)
flood_comb <- cbind(flood, elev_comb, slope_comb, water_comb, fac_comb) 

flood_comb2 <- cbind(flood, elev_comb [, -1], slope_comb [, -1], water_comb [, -1], fac_comb [, -1]) %>%
  rename(mean_elev = elev_comb [, -1])

floodPlotVariables <- 
  flood_comb %>%
  as.data.frame() %>%
  select(flood, mean_elev, max_slope, min_dist_water, max_fac) %>%
  gather(variable, value, -flood)
```

```{r plot_variables}

# need to check the labels for flood and not flood 

ggplot(floodPlotVariables %>%
         group_by(flood, variable) %>%
         summarize(mean = mean(value))) + 
     geom_bar(aes(as.factor(flood), 
                  mean, 
                  fill=as.factor(flood)),
              stat="identity") + 
     facet_wrap(~variable) +
     scale_fill_manual(values = c("dark blue", "dark green"),
                      labels = c("Not Flood","Flood"),
                      name = "") +
    labs(x="Flood", y="Value")


# plot by count 
ggplot()

```





