---
title: "Landuse_mapping"
output: html_document
date: "2024-04-01"
---


# Setup
```{r setup, warning = FALSE, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(pscl)
library(plotROC)
library(pROC)
library(sf)
library(tidyverse)
library(knitr)
library(kableExtra)
library(tigris)
library(viridis)
library(ggplot2)
```

```{r themes}
mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())
```

```{r calgary}
calgary_fishnet<-st_read("https://raw.githubusercontent.com/luyiiw/LUEM/main/Calgary_JSON/Calgary_Fishnet.json")
calgary_boundary<-st_read("https://raw.githubusercontent.com/luyiiw/LUEM/main/Calgary_JSON/Calgary_Boundary.json")

```

```{r Raster cleaning for Calgary Dependent}

library(raster)
library(rgdal)

#Inundation Calgary
dependent <- raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/calgary_raster/dependent.tif")
dependent_df <- as.data.frame(dependent, xy = TRUE)

fishnet_shp<- st_read("C:/Users/USER/Desktop/LandUseModeling/Assignment3/Calgary/fishnet_boundary.shp")
st_geometry_type(fishnet_shp)

calfishnet_shp <- st_zm(fishnet_shp, drop = TRUE)

clipped_depen <- mask(dependent,calfishnet_shp)
clip_df <-as.data.frame(clipped_depen, xy=TRUE)

ggplot() +
  geom_raster(data = clip_df, aes(x = x, y = y, fill = dependent)) +  # Raster layer
  geom_sf(data = calgary_fishnet, color = "grey", fill = NA) +  # Spatial fishnet overlay
  scale_fill_continuous(name = "Flood Status", low = "yellow", high = "red",na.value = "transparent",
                        breaks = c(0, 1), labels = c("Not inundation", "Inundation")) +
  coord_sf() +  # Explicitly use spatial coordinates
  labs(title = "Past Flooding in Calgary") +
  mapTheme


clip_df$dependent <- factor(clip_df$dependent)

ggplot() +
  geom_raster(data = clip_df, aes(x = x, y = y, fill = dependent)) + 
  geom_sf(data = calgary_fishnet, color = "grey", fill = NA) + 
  geom_tile() +  # Use geom_tile for raster data
  scale_fill_manual(values = c("1" = "yellow", "0" = "red"), 
                    labels = c("1" = "Inundation", "0" = "Not Inundation"), 
                    name = "Flood Status",
                     na.value = "transparent") +
  coord_sf() +  # Explicitly use spatial coordinates
  labs(title = "Past Flooding in Calgary") +
  mapTheme
##Design Refinement Later
```


# Exploratory Analysis_Calgary
```{r independent_flowaccumulation}
library(viridis)
#Flow accumulation
calgary_fac<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/calgary_raster/Calgary_fac.tif")
clipped_cal_fac <- mask(calgary_fac,calfishnet_shp)

cal_fac_df <-as.data.frame(clipped_cal_fac, xy=TRUE)
library(viridis) 
ggplot() +
    geom_raster(data = cal_fac_df , aes(x = x, y = y, fill =Calgary_fac)) +
 scale_fill_viridis_c(name = "Flow Accumulation", option = "inferno", na.value = "transparent",
  limits = c(min(cal_fac_df$Calgary_fac, na.rm = TRUE), max(cal_fac_df$Calgary_fac, na.rm = TRUE) *1.01))+
  coord_sf() +
  labs(title = "Flood Accumulation in Calgary, Canada") +
  mapTheme
```
```{r independent_permeability}  
##permeability  
calgary_perme<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/calgary_raster/calgary_perme.tif")

clipped_cal_perme <- mask(calgary_perme,calfishnet_shp)
cal_perme_df <-as.data.frame(clipped_cal_perme, xy=TRUE)

cal_perme_df$calgary_perme<-factor(cal_perme_df$calgary_perme)

ggplot() +
  geom_raster(data = cal_perme_df, aes(x = x, y = y, fill = calgary_perme)) + 
  geom_tile() +  # Use geom_tile for raster data
  scale_fill_manual(values = c("1" = "#D3D3D3", "0" = "#00008B"), 
                    labels = c("1" = "Impermeable", "0" = "Permeable"), 
                    name = "Permeability Status",
                     na.value = "transparent") +
  coord_sf() +  # Explicitly use spatial coordinates
  labs(title = "Permeability by Land Cover in Calgary,Canada") +
  mapTheme
```   
```{r independent_Water}  
##Distance from water Body
calgary_water<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/calgary_raster/calgary_water.tif")
clipped_cal_water <- mask(calgary_water,calfishnet_shp)
cal_water_df <-as.data.frame(clipped_cal_water, xy=TRUE)


ggplot() +
  geom_raster(data = cal_water_df, aes(x = x, y = y, fill = calgary_water)) +
  scale_fill_gradient(name = "Euclidean Distance",
                      low = "lightblue", high = "darkblue",
                      na.value = "transparent",
                      limits = c(NA, 4000)) +  # Explicitly set the upper limit to 4000
  coord_sf() +
  labs(title = "Distance from Water Body in Calgary, Canada") +
  mapTheme
```   
```{r independent_Slope}  
##slope

calgary_slope<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/calgary_raster/calgary_slope.tif")
clipped_cal_slope <- mask(calgary_slope,calfishnet_shp)
cal_slope_df <-as.data.frame(clipped_cal_slope, xy=TRUE)


ggplot() +
    geom_raster(data = cal_slope_df , aes(x = x, y = y, fill =calgary_slope)) +
    scale_fill_gradient(name = "Slope",
                      low = "#FDE6CF", high = "#CC2D20",
                      na.value = "transparent",
                      limits = c(NA, 28)) +
  coord_sf() +
      labs(title = "Slope in Calgary, Canada") +
  mapTheme

```   
```{r independent_Elevation}  
##Elevation

calgary_dem<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/calgary_raster/calgary_dem.tif")

clipped_cal_dem <- mask(calgary_dem,calfishnet_shp)
cal_dem_df <-as.data.frame(clipped_cal_dem, xy=TRUE)

lowest_value <- 970
highest_value <- 1290

ggplot() +
  geom_raster(data = cal_dem_df, aes(x = x, y = y, fill = calgary_dem)) +
  scale_fill_viridis_c(name = "Elevation (m)",
                       na.value = "transparent",
                       limits = c(lowest_value, highest_value),  # Set explicit limits to include your specific range
                       breaks = c(lowest_value, (lowest_value+highest_value)/2, highest_value),  # Include mid-point for clarity
                       labels = c(as.character(lowest_value), as.character((lowest_value+highest_value)/2), as.character(highest_value))) +  # Custom labels for the breaks
  coord_sf() +
  labs(title = "Elevation in Calgary, Canada") +
mapTheme


ggplot() +
  geom_raster(data = cal_dem_df, aes(x = x, y = y, fill = calgary_dem)) +  # Visualize DEM data
  geom_sf(data = calgary_fishnet, color = "grey", fill = NA) +  # Add fishnet overlay without fill
    scale_fill_viridis_c(name = "Elevation (m)", na.value = "transparent")+  # Apply viridis color scale to DEM
  coord_sf() +  # Use spatial coordinates
  labs(title = "Elevation in Calgary, Canada") +  # Title for the plot
   mapTheme

```  
# Exploratory Analysis_Denver
```{r cleaning for Denver Fishnet}

denver_fishnet<-st_read("https://raw.githubusercontent.com/luyiiw/LUEM/main/Denver_JSON/denver_fishnet.json")
denver_boundary<-st_read("https://raw.githubusercontent.com/luyiiw/LUEM/main/Denver_JSON/denver_boundary.json")

ggplot() + 
  geom_sf(data=denver_boundary,fill=NA, color="blue",size=0.5) +
  geom_sf(data=denver_fishnet,color="red",size=0.2) +
  labs(title="Denver Fishnet")+
  mapTheme

##cleaning Denver Boundary
fishnet_shp_den<- st_read("C:/Users/USER/Desktop/LandUseModeling/Assignment3/Denver/denver_boundary.shp")
st_geometry_type(fishnet_shp_den)

denfishnet_shp <- st_zm(fishnet_shp_den, drop = TRUE)
```  

```{r independent_flowaccumulation}
#Denver Fac
den_fac<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/denver_rast/den_fac.tif")
clipped_den_fac <- mask(den_fac,denfishnet_shp )
den_fac_df <-as.data.frame(clipped_den_fac , xy=TRUE)



ggplot() +
    geom_raster(data = den_fac_df , aes(x = x, y = y, fill =den_fac)) +
 scale_fill_viridis_c(name = "Flow Accumulation", option = "inferno", na.value = "transparent",
  limits = c(min(den_fac_df$den_fac, na.rm = TRUE), max(den_fac_df$den_fac, na.rm = TRUE) *1.01))+
  coord_sf() +
  labs(title = "Flood Accumulation in Denver, Colorado") +
  mapTheme

```    
```{r independent_permeability}   
##permeability  
den_perme<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/denver_rast/den_perme.tif")
clipped_den_perme <- mask(den_perme,denfishnet_shp)
den_perme_df <-as.data.frame(clipped_den_perme, xy=TRUE)

den_perme_df$den_perme<-factor(den_perme_df$den_perme)

ggplot() +
  geom_raster(data = den_perme_df, aes(x = x, y = y, fill = den_perme)) + 
  geom_tile() +  # Use geom_tile for raster data
  scale_fill_manual(values = c("1" = "#D3D3D3", "0" = "#00008B"), 
                    labels = c("1" = "Impermeable", "0" = "Permeable"), 
                    name = "Permeability Status",
                     na.value = "transparent") +
  coord_sf() +  # Explicitly use spatial coordinates
  labs(title = "Permeability by Land Cover in Denver, Colorado") +
  mapTheme
```    
```{r independent_Water}  
##Distance from water Body
den_water<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/denver_rast/den_water.tif")

clipped_den_water <- mask(den_water,denfishnet_shp)
den_water_df <-as.data.frame(clipped_den_water, xy=TRUE)


ggplot() +
  geom_raster(data = den_water_df , aes(x = x, y = y, fill = den_water)) +
  scale_fill_gradient(name = "Euclidean Distance",
                      low = "lightblue", high = "darkblue",
                      na.value = "transparent",
                      limits = c(NA, 5000)) +  # Explicitly set the upper limit to 4000
  coord_sf() +
  labs(title = "Distance from Water Body in Denver, Colorado") +
  mapTheme
```
```{r independent_Slope}  
##slope

denver_slope<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/denver_rast/den_slope.tif")

clipped_den_slope <- mask(denver_slope,denfishnet_shp)
den_slope_df <-as.data.frame(clipped_den_slope, xy=TRUE)

ggplot() +
    geom_raster(data = den_slope_df , aes(x = x, y = y, fill =den_slope)) +
    scale_fill_gradient(name = "Slope",
                      low = "#FDE6CF", high = "#CC2D20",
                      na.value = "transparent",
                      limits = c(NA, 45)) +
  coord_sf() +
      labs(title = "Slope in Denver, Colorado") +
  mapTheme

``` 
```{r independent_Elevation}
##Elevation

den_dem<-raster("C:/Users/USER/Desktop/LandUseModeling/Assignment3/denver_rast/den_dem.tif")

clipped_den_dem <- mask(den_dem,denfishnet_shp)
den_dem_df <-as.data.frame(clipped_den_dem , xy=TRUE)

lowest_value_den <- 1551
highest_value_den <- 1754

ggplot() +
  geom_raster(data = den_dem_df, aes(x = x, y = y, fill = den_dem)) +
  geom_sf(data = denver_fishnet, color = "grey", fill = NA) +
  scale_fill_viridis_c(name = "Elevation (m)",
                       na.value = "transparent",
                       limits = c(lowest_value_den, highest_value_den),  # Set explicit limits to include your specific range
                       breaks = c(lowest_value_den, (lowest_value_den+highest_value_den)/2, highest_value_den),  # Include mid-point for clarity
                       labels = c(as.character(lowest_value_den), as.character((lowest_value_den+highest_value_den)/2), as.character(highest_value_den))) +  # Custom labels for the breaks
  coord_sf() +
  labs(title = "Elevation in Denver, Colorado") +
mapTheme


``` 

calgary_fishnet01<-calgary_fishnet%>%mutate(calgary_fishnet$)

calgary_fishnet$OBJECTID <- 1:nrow(calgary_fishnet)
  
  
  
  
  
  
  